### ISSUE TITLE
Question about core modules

### ISSUE THREAD

**Issue by catavatars** [rm-code/Hoost#1]
hello, i've been looking over this game and it seems really interesting, however the code is very confusing

could you please explain what tile.lua, tilefactory.lua and worldpainter.lua do?

**Comment by rm-code** [comment]
Hi,

> however the code is very confusing

That's because the game is in early development and a lot of the code I am writing at the moment is _just _ supposed to work. Documentation and clean up are done every now and then 😉 

> could you please explain what tile.lua, tilefactory.lua and worldpainter.lua do?

The __Tile__ class describes a square on the tile grid (aka the map). It is a container for most of the stuff that's going on in the world.

The __TileFactory__ is just a class which knows how to put together __Tile__s from a template.

The __WorldPainter__ currently is taking care of drawing the whole game.

Cheers,
Robert

**Comment by catavatars** [comment]
ok thanks, that cleared things up a bit :)
